"""Agregando campo tipo en tabla informacion_terceros

Revision ID: 07257e357ebe
Revises: 3c80078217f2
Create Date: 2025-01-20 16:18:49.399682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07257e357ebe'
down_revision = '3c80078217f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informacion_terceros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informacion_terceros', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
