"""Actualización esquema BD, agregando tablas.

Revision ID: 25c9654b54b9
Revises: be1cc67dc74f
Create Date: 2025-01-04 14:22:21.228033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c9654b54b9'
down_revision = 'be1cc67dc74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('tax_level_code', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city_name', sa.String(length=255), nullable=True),
    sa.Column('country_subentity', sa.String(length=255), nullable=True),
    sa.Column('country_subentity_code', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('electronic_mail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'empresa', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('empresa')
    # ### end Alembic commands ###
