"""Initial migration

Revision ID: 35635fd420d7
Revises: 6a1dd5d1c12a
Create Date: 2025-01-03 13:44:41.332501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35635fd420d7'
down_revision = '6a1dd5d1c12a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=150), nullable=True),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('email_contacto', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_empresa')
    )
    op.create_table('informacion_terceros',
    sa.Column('id_terceros', sa.Integer(), nullable=False),
    sa.Column('identificacion', sa.String(), nullable=True),
    sa.Column('tipo_persona', sa.String(length=20), nullable=True),
    sa.Column('nombre_razon_social', sa.String(length=100), nullable=True),
    sa.Column('representante_legal', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=40), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('actividad_economica', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_terceros')
    )
    op.create_table('personas',
    sa.Column('id_persona', sa.String(length=20), nullable=False),
    sa.Column('primer_nombre', sa.String(length=20), nullable=True),
    sa.Column('primer_apellido', sa.String(length=20), nullable=True),
    sa.Column('tipo_documento', sa.Integer(), nullable=True),
    sa.Column('numero_documento', sa.Integer(), nullable=True),
    sa.Column('telefono_contacto', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=True),
    sa.Column('descripcion_rol', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('id_persona', sa.String(length=20), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('personas')
    op.drop_table('informacion_terceros')
    op.drop_table('empresa')
    # ### end Alembic commands ###
