"""Agregando tablas XML

Revision ID: 3c80078217f2
Revises: 
Create Date: 2025-01-20 11:20:10.387708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c80078217f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos_xml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=20), nullable=True),
    sa.Column('registration_name', sa.String(length=100), nullable=True),
    sa.Column('tax_level_code', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('city_name', sa.String(length=50), nullable=True),
    sa.Column('country_subentity', sa.String(length=50), nullable=True),
    sa.Column('country_subentity_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('country_name', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('electronic_mail', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturacion_xml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubl_version_id', sa.String(length=10), nullable=True),
    sa.Column('customization_id', sa.String(length=10), nullable=True),
    sa.Column('profile_id', sa.String(length=100), nullable=True),
    sa.Column('profile_execution_id', sa.String(length=10), nullable=True),
    sa.Column('document_id', sa.String(length=20), nullable=True),
    sa.Column('uuid', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issue_time', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_type_code', sa.String(length=10), nullable=True),
    sa.Column('document_currency_code', sa.String(length=5), nullable=True),
    sa.Column('line_count_numeric', sa.String(length=10), nullable=True),
    sa.Column('supplier_id', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impuestos_xml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxable_amount', sa.String(length=20), nullable=True),
    sa.Column('tax_amount', sa.String(length=20), nullable=True),
    sa.Column('tax_percent', sa.String(length=10), nullable=True),
    sa.Column('tax_scheme_id', sa.String(length=10), nullable=True),
    sa.Column('tax_scheme_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas_xml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_xml',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nro', sa.String(length=10), nullable=True),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('um', sa.String(length=20), nullable=True),
    sa.Column('cantidad', sa.String(length=20), nullable=True),
    sa.Column('precio_unitario', sa.String(length=20), nullable=True),
    sa.Column('precio_venta', sa.String(length=20), nullable=True),
    sa.Column('descuento_detalle', sa.String(length=20), nullable=True),
    sa.Column('recargo_detalle', sa.String(length=20), nullable=True),
    sa.Column('iva', sa.String(length=20), nullable=True),
    sa.Column('inc', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos_xml')
    op.drop_table('notas_xml')
    op.drop_table('impuestos_xml')
    op.drop_table('facturacion_xml')
    op.drop_table('datos_xml')
    # ### end Alembic commands ###
