"""Initial migration

Revision ID: 493dbb69692b
Revises: beb9736580d2
Create Date: 2025-01-03 13:26:02.912356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493dbb69692b'
down_revision = 'beb9736580d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
