"""Descripción de la migración

Revision ID: 50431717256a
Revises: 
Create Date: 2025-01-06 14:53:27.003276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50431717256a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('tax_level_code', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city_name', sa.String(length=255), nullable=True),
    sa.Column('country_subentity', sa.String(length=255), nullable=True),
    sa.Column('country_subentity_code', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('electronic_mail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('informacion_terceros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('tax_level_code', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city_name', sa.String(length=255), nullable=True),
    sa.Column('country_subentity', sa.String(length=255), nullable=True),
    sa.Column('country_subentity_code', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('electronic_mail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('personas',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=20), nullable=True),
    sa.Column('primer_apellido', sa.String(length=20), nullable=True),
    sa.Column('tipo_documento', sa.String(length=10), nullable=True),
    sa.Column('numero_documento', sa.String(length=20), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=True),
    sa.Column('descripcion_rol', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('facturacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubl_version_id', sa.String(length=50), nullable=True),
    sa.Column('customization_id', sa.String(length=50), nullable=True),
    sa.Column('profile_id', sa.String(length=255), nullable=True),
    sa.Column('profile_execution_id', sa.String(length=50), nullable=True),
    sa.Column('document_id', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issue_time', sa.Time(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_type_code', sa.String(length=50), nullable=True),
    sa.Column('document_currency_code', sa.String(length=50), nullable=True),
    sa.Column('line_count_numeric', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['informacion_terceros.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('invoice_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.String(length=50), nullable=True),
    sa.Column('invoiced_quantity', sa.String(length=50), nullable=True),
    sa.Column('line_extension_amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['facturacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_line')
    op.drop_table('usuarios')
    op.drop_table('facturacion')
    op.drop_table('roles')
    op.drop_table('personas')
    op.drop_table('informacion_terceros')
    op.drop_table('empresa')
    # ### end Alembic commands ###
