"""Initial migration

Revision ID: 6a1dd5d1c12a
Revises: 493dbb69692b
Create Date: 2025-01-03 13:34:46.893147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1dd5d1c12a'
down_revision = '493dbb69692b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
