"""Ajustar tamaño del campo document_id

Revision ID: be1cc67dc74f
Revises: 63f8370e8c7c
Create Date: 2025-01-04 14:14:20.371331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1cc67dc74f'
down_revision = '63f8370e8c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
