"""Corregir tipos de datos en las tablas personas y usuarios

Revision ID: f9823892ae89
Revises: 35635fd420d7
Create Date: 2025-01-03 17:59:43.134490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9823892ae89'
down_revision = '35635fd420d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=20), nullable=True),
    sa.Column('primer_apellido', sa.String(length=20), nullable=True),
    sa.Column('tipo_documento', sa.String(length=10), nullable=True),
    sa.Column('numero_documento', sa.String(length=20), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=True),
    sa.Column('descripcion_rol', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('personas')
    # ### end Alembic commands ###
