"""change

Revision ID: fbde03fa6b17
Revises: 9a66bfe4d1ed
Create Date: 2025-01-10 14:52:25.103603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbde03fa6b17'
down_revision = '9a66bfe4d1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campo', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('valor', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('facturacion_customer_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('facturacion_supplier_id_fkey', type_='foreignkey')
        batch_op.drop_column('issue_time')
        batch_op.drop_column('document_id')
        batch_op.drop_column('invoice_type_code')
        batch_op.drop_column('document_currency_code')
        batch_op.drop_column('profile_id')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('ubl_version_id')
        batch_op.drop_column('issue_date')
        batch_op.drop_column('due_date')
        batch_op.drop_column('uuid')
        batch_op.drop_column('line_count_numeric')
        batch_op.drop_column('customization_id')
        batch_op.drop_column('supplier_id')
        batch_op.drop_column('profile_execution_id')

    with op.batch_alter_table('informacion_terceros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actividad_economica', sa.String(length=255), nullable=True))
        batch_op.alter_column('company_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('tax_level_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('country_subentity_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('telephone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint('informacion_terceros_company_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('informacion_terceros', schema=None) as batch_op:
        batch_op.create_unique_constraint('informacion_terceros_company_id_key', ['company_id'])
        batch_op.alter_column('telephone',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('country_subentity_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('tax_level_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('company_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('actividad_economica')

    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_execution_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customization_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('line_count_numeric', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('issue_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ubl_version_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('profile_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('document_currency_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_type_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('document_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('issue_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('facturacion_supplier_id_fkey', 'empresa', ['supplier_id'], ['id'])
        batch_op.create_foreign_key('facturacion_customer_id_fkey', 'informacion_terceros', ['customer_id'], ['id'])
        batch_op.drop_column('valor')
        batch_op.drop_column('campo')

    # ### end Alembic commands ###
